from typing import Annotated
from semantic_kernel.functions.kernel_function_decorator import kernel_function

class PromptPlugin:
    def __init__(self, initial_instruction: str = ""):
        self.last_instruction: str = initial_instruction
        self.last_rouge_score: float = 0.0
        self.last_summary: str = ""

    @kernel_function(
        name="GeLastInstructionRougeScore",
        description="Get the ROUGE score associated with the last instruction."
    )
    async def get_best_instruction_rouge_score(self) -> Annotated[float, "ROUGE score of best instruction"]:
        return self.last_rouge_score

    @kernel_function(
        name="GetLastSummary",
        description="Retrieve the most recent summary produced by the Summarizer."
    )
    async def get_last_summary(self) -> Annotated[str, "Most recent summary produced by the Summarizer"]:
        return self.last_summary

    @kernel_function(
        name="SetLastSummary",
        description="Set or update the most recent summary generated by the Summarizer."
    )
    async def set_last_summary(
        self,
        summary: Annotated[str, "The latest summary to store"]
    ):
        self.last_summary = summary

    @kernel_function(
        name="GetLastInstruction",
        description="Retrieve the most recent instruction proposed by the Teacher."
    )
    async def get_last_instruction(self) -> Annotated[str, "Last instruction proposed"]:
        return self.last_instruction

    @kernel_function(
        name="SetLastInstruction",
        description="Set or update the most recent instruction proposed by the Teacher."
    )
    async def set_last_instruction(
        self,
        instruction: Annotated[str, "Latest instruction to store"]
    ):
        self.last_instruction = instruction

    @kernel_function(
        name="UpdateRougeScoreLastInstruction",
        description="Update the value of ROUGE score of the last instruction."
    )
    async def update_rouge_instruction(
        self,
        rouge_score: Annotated[float, "ROUGE score of the candidate instruction"]
    ):
        self.last_rouge_score = rouge_score

